# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-10 22:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DJ', '0003_entry_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topic',
            old_name='data_added',
            new_name='date_added',
        ),
    ]
